
//create table

CREATE TABLE ETL_LOG_PDI
    (LOG_ID NUMBER
    ,TASK_ID VARCHAR2(100)
    ,ETL_FREQUENCY VARCHAR2(10)
    ,ETL_STATUS NUMBER
    ,ETL_TIME NUMBER
    ,BEGIN_TIME DATE
    ,END_TIME DATE
    ,LOG CLOB
    );

CREATE TABLE ETL_LOG_PLSQL
    (LOG_ID NUMBER
    ,TASK_ID VARCHAR2(100)
    ,ETL_FREQUENCY VARCHAR2(10)
    ,ETL_STATUS NUMBER
    ,ETL_TIME NUMBER
    ,BEGIN_TIME DATE
    ,END_TIME DATE
    ,LOG_SQLERRM  VARCHAR2(500)
    ,LOG_ERROR_STACK VARCHAR2(4000)
    ,LOG_BACKTRACE VARCHAR2(4000)
    );

CREATE TABLE ETL_LOG_ALL
    (TASK_ID VARCHAR2(100)
	,TASK_TYPE VARCHAR2(20)
    ,ETL_FREQUENCY VARCHAR2(10)
    ,ETL_STATUS NUMBER
    ,ETL_TIME NUMBER
    ,BEGIN_TIME DATE
    ,END_TIME DATE
    );
	
CREATE TABLE ETL_TASK
    (TASK_ID VARCHAR2(100)
    ,TASK_NAME VARCHAR2(100)
	,TASK_TYPE VARCHAR2(20)
    ,ETL_FREQUENCY VARCHAR2(10)
    ,PARENT_TASK_LIST VARCHAR2(1000)
    ,VALID_FLAG NUMBER
    );
